### ISSUE TITLE
Map working on Android but crashes on iOS

### ISSUE THREAD

**Issue by mytahir** [themronion/Maui.GoogleMaps#10]
### VERSIONS

* Maui.GoogleMaps - 5.0.1
* .NET SDK - 7.x.x

### IDE

- [ ] Rider
- [ ] Visual Studio
- [x] Visual Studio for Mac

### PLATFORMS

- [ ] Android
- [x] iOS

### ACTUAL BEHAVIOR
```
// Write about of your problem
I test the Map on Android and it is working fine, but when my friend runs it on Mac using Simulator, the map crashes and also test on Physical iPhone and the same problem. 
```

### ACTUAL SCREENSHOTS/STACKTRACE

```
// Paste stacktrace/screenshots/recordings
at ObjCRuntime.ThrowHelper.ThrowArgumentNullException(String argumentName)
   at ObjCRuntime.NativeObjectExtensions.GetNonNullHandle(INativeObject self, String argumentName)
   at CoreAnimation.CALayer.RenderInContext(CGContext ctx)
   at Maui.GoogleMaps.Utils.ConvertViewToImage(UIView view)
   at Maui.GoogleMaps.Logics.iOS.PinLogic.<>c__DisplayClass31_0.<OnUpdateIconView>b__0()
   at Foundation.NSObject.InvokeOnMainThread(Action action)
   at Maui.GoogleMaps.Logics.iOS.PinLogic.OnUpdateIconView(Pin outerItem, Marker nativeItem)
   at Maui.GoogleMaps.Logics.iOS.PinLogic.CreateNativeItem(Pin outerItem)
   at Maui.GoogleMaps.Logics.DefaultLogic`3[[Maui.GoogleMaps.Pin, Maui.GoogleMaps, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Google.Maps.Marker, Google.Maps, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Google.Maps.MapView, Google.Maps, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].AddItems(IList newItems)
   at Maui.GoogleMaps.Logics.BaseLogic`1[[Google.Maps.MapView, Google.Maps, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs notifyCollectionChangedEventArgs)
   at System.Collections.ObjectModel.ObservableCollection`1[[Maui.GoogleMaps.Pin, Maui.GoogleMaps, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1[[Maui.GoogleMaps.Pin, Maui.GoogleMaps, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].OnCollectionChanged(NotifyCollectionChangedAction action, Object item, Int32 index)
   at System.Collections.ObjectModel.ObservableCollection`1[[Maui.GoogleMaps.Pin, Maui.GoogleMaps, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].InsertItem(Int32 index, Pin item)
   at System.Collections.ObjectModel.Collection`1[[Maui.GoogleMaps.Pin, Maui.GoogleMaps, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].Add(Pin item)
   at MauiMap.MainPage.OnAppearing() in /Users/sohel/Downloads/MauiMap/MauiMap/MainPage.xaml.cs:line 50
   at ObjCRuntime.Runtime.ThrowException(IntPtr gchandle)
   at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName)
   at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass)
   at MauiMap.Program.Main(String[] args) in /Users/sohel/Downloads/MauiMap/MauiMap/Platforms/iOS/Program.cs:line 13
```

### EXPECTED BEHAVIOR 
```
// Write about the behavior what you expected
```

### HOW TO REPRODUCE
```
// code and steps to reproduce
```

1. 
2. 
3.

**Comment by themronion** [comment]
Send me a test project to reproduce, please

**Comment by mytahir** [comment]
here is the sample:
https://github.com/mytahir/MauiMap

**Comment by mytahir** [comment]
> Send me a test project to reproduce, please

Here is the test project:
https://github.com/mytahir/MauiMap

**Comment by mytahir** [comment]
@themronion

**Comment by mytahir** [comment]
Do i have to downgrade my iOS Version? @themronion

**Comment by themronion** [comment]
the test project is private, please make it an open repo

**Comment by themronion** [comment]
Closing as no info to reproduce was provided
