### ISSUE TITLE
An error occurred: 'Could not create an native instance of the type 'Google.Maps.MapView': the native class hasn't been loaded.

### ISSUE THREAD

**Issue by afilatoff** [themronion/Maui.GoogleMaps#46]
### VERSIONS

* Maui.GoogleMaps - 5.0.3
* .NET SDK - 8.0

### IDE
Microsoft Visual Studio Community 2022 (64-bit) 
### PLATFORMS

- [ ] Android
- [x] iOS

### ACTUAL BEHAVIOR
The app has been terminated.

### ACTUAL SCREENSHOTS/STACKTRACE
[0:] An error occurred: 'Could not create an native instance of the type 'Google.Maps.MapView': the native class hasn't been loaded.
It is possible to ignore this condition by setting ObjCRuntime.Class.ThrowOnInitFailure to false.'. Callstack: '   at Foundation.NSObject.InitializeObject(Boolean alloced) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/Foundation/NSObject2.cs:line 363
   at Foundation.NSObject..ctor(NSObjectFlag x) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/Foundation/NSObject2.cs:line 214
   at UIKit.UIResponder..ctor(NSObjectFlag t) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/build/dotnet/ios/generated-sources/UIKit/UIResponder.g.cs:line 75
   at UIKit.UIView..ctor(NSObjectFlag t) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/build/dotnet/ios/generated-sources/UIKit/UIView.g.cs:line 89
   at Google.Maps.MapView..ctor(CGRect frame)
   at Maui.GoogleMaps.Handlers.MapHandler.CreatePlatformView()
   at Microsoft.Maui.Handlers.ViewHandler`2[[Maui.GoogleMaps.Map, Maui.GoogleMaps, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Google.Maps.MapView, Google.Maps, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].OnCreatePlatformView()
   at Microsoft.Maui.Handlers.ViewHandler.OnCreatePlatformElement()
   at Microsoft.Maui.Handlers.ElementHandler.CreatePlatformElement()
   at Microsoft.Maui.Handlers.ElementHandler.SetVirtualView(IElement view)
   at Microsoft.Maui.Handlers.ViewHandler`2[[Maui.GoogleMaps.Map, Maui.GoogleMaps, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Google.Maps.MapView, Google.Maps, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].SetVirtualView(IView view)
   at Microsoft.Maui.Handlers.ViewHandler`2[[Maui.GoogleMaps.Map, Maui.GoogleMaps, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Google.Maps.MapView, Google.Maps, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].SetVirtualView(IElement view)
   at Microsoft.Maui.Controls.Element.SetHandler(IElementHandler newHandler)
   at Microsoft.Maui.Controls.Element.set_Handler(IElementHandler value)
   at Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IElement.set_Handler(IElementHandler value)
   at Microsoft.Maui.Platform.ElementExtensions.ToHandler(IElement view, IMauiContext context)
   at Microsoft.Maui.Platform.ElementExtensions.ToPlatform(IElement view, IMauiContext context)
   at Microsoft.Maui.Handlers.ContentViewHandler.UpdateContent(IContentViewHandler handler)
   at Microsoft.Maui.Handlers.ContentViewHandler.MapContent(IContentViewHandler handler, IContentView page)
   at Microsoft.Maui.PropertyMapper`2.<>c__DisplayClass5_0[[Microsoft.Maui.IContentView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Handlers.IContentViewHandler, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<Add>b__0(IElementHandler h, IElement v)
   at Microsoft.Maui.PropertyMapper.UpdatePropertyCore(String key, IElementHandler viewHandler, IElement virtualView)
   at Microsoft.Maui.PropertyMapper.UpdateProperties(IElementHandler viewHandler, IElement virtualView)
   at Microsoft.Maui.Handlers.ElementHandler.SetVirtualView(IElement view)
   at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.IContentView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Platform.ContentView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].SetVirtualView(IView view)
   at Microsoft.Maui.Handlers.ContentViewHandler.SetVirtualView(IView view)
   at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.IContentView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Platform.ContentView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].SetVirtualView(IElement view)
   at Microsoft.Maui.Controls.Element.SetHandler(IElementHandler newHandler)
   at Microsoft.Maui.Controls.Element.set_Handler(IElementHandler value)
   at Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IElement.set_Handler(IElementHandler value)
   at Microsoft.Maui.Platform.ElementExtensions.ToHandler(IElement view, IMauiContext context)
   at Microsoft.Maui.Platform.ElementExtensions.ToPlatform(IElement view, IMauiContext context)
   at Microsoft.Maui.Handlers.LayoutHandler.SetVirtualView(IView view)
   at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.ILayout, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Platform.LayoutView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].SetVirtualView(IElement view)
   at Microsoft.Maui.Controls.Element.SetHandler(IElementHandler newHandler)
   at Microsoft.Maui.Controls.Element.set_Handler(IElementHandler value)
   at Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IElement.set_Handler(IElementHandler value)
   at Microsoft.Maui.Platform.ElementExtensions.ToHandler(IElement view, IMauiContext context)
   at Microsoft.Maui.Platform.ElementExtensions.ToPlatform(IElement view, IMauiContext context)
   at Microsoft.Maui.Handlers.LayoutHandler.SetVirtualView(IView view)
   at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.ILayout, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Platform.LayoutView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].SetVirtualView(IElement view)
   at Microsoft.Maui.Controls.Element.SetHandler(IElementHandler newHandler)
   at Microsoft.Maui.Controls.Element.set_Handler(IElementHandler value)
   at Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IElement.set_Handler(IElementHandler value)
   at Microsoft.Maui.Platform.ElementExtensions.ToHandler(IElement view, IMauiContext context)
   at Microsoft.Maui.Platform.ElementExtensions.ToPlatform(IElement view, IMauiContext context)
   at Microsoft.Maui.Handlers.ContentViewHandler.UpdateContent(IContentViewHandler handler)
   at Microsoft.Maui.Handlers.ContentViewHandler.MapContent(IContentViewHandler handler, IContentView page)
   at Microsoft.Maui.PropertyMapper`2.<>c__DisplayClass5_0[[Microsoft.Maui.IContentView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Handlers.IContentViewHandler, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<Add>b__0(IElementHandler h, IElement v)
   at Microsoft.Maui.PropertyMapper.UpdatePropertyCore(String key, IElementHandler viewHandler, IElement virtualView)
   at Microsoft.Maui.PropertyMapper.UpdateProperties(IElementHandler viewHandler, IElement virtualView)
   at Microsoft.Maui.Handlers.ElementHandler.SetVirtualView(IElement view)
   at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.IContentView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Platform.ContentView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].SetVirtualView(IView view)
   at Microsoft.Maui.Handlers.ContentViewHandler.SetVirtualView(IView view)
   at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.IContentView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Platform.ContentView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].SetVirtualView(IElement view)
   at Microsoft.Maui.Controls.Element.SetHandler(IElementHandler newHandler)
   at Microsoft.Maui.Controls.Element.set_Handler(IElementHandler value)
   at Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IElement.set_Handler(IElementHandler value)
   at Microsoft.Maui.Platform.ElementExtensions.ToHandler(IElement view, IMauiContext context)
   at Microsoft.Maui.Platform.ViewExtensions.ToHandler(IView view, IMauiContext context)
   at Microsoft.Maui.Controls.Platform.Compatibility.ShellSectionRootRenderer.SetPageRenderer(Page page, ShellContent shellContent)
   at Microsoft.Maui.Controls.Platform.Compatibility.ShellSectionRootRenderer.LoadRenderers()
   at Microsoft.Maui.Controls.Platform.Compatibility.ShellSectionRootRenderer.ViewDidLoad()
   at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:line 58
   at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:line 94
   at Towing.Program.Main(String[] args) in C:\dev\Towing\Platforms\iOS\Program.cs:line 13
   at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)'
The app has been terminated.

### EXPECTED BEHAVIOR 
[Write about the behavior what you expected]

### HOW TO REPRODUCE
[code and steps to reproduce]

1. installed NuGet\Install-Package Onion.Maui.GoogleMaps -Version 5.0.3
2. Followed all recommendations proper usage of Maui.GoogleMaps
3. Tried to show Map  on the screen
4. App terminated

What did I miss?

**Comment by plppp2001** [comment]
It works fine, I suggest first run the example project. Look at the code there.

**Comment by afilatoff** [comment]
It does not work for me - this is the main reason I posted this issue. Any ideas what can cause 'Could not create an native instance of the type 'Google.Maps.MapView': the native class hasn't been loaded." error?

I tried to run the example project - this is as far as I can go - I can put breakpoint on the buttons, I can step thru the code, but I don't see the map (well... at least it's not crushing)
![image](https://github.com/themronion/Maui.GoogleMaps/assets/65758012/5aef6e6e-836c-4758-bae6-34204857b79f)

**Comment by themronion** [comment]
Please don't use Hot Restart.

**Comment by afilatoff** [comment]
Disable Hot Restart - no difference, the same error "An error occurred: 'Could not create an native instance of the type 'Google.Maps.MapView': the native class hasn't been loaded."

**Comment by themronion** [comment]
Build on a mac, not on windows with a connected iphone. I think u mistakenly thought i told u to disable Hot reload. Hot restart and hot reload are different things

**Comment by afilatoff** [comment]
Yes, you are correct - hot restart and hot reload are different, but disabling hot restart I lost ability to debug on local device. Is there a way to use local devices without hot restart?

**Comment by themronion** [comment]
Yes, use a macbook for iOS development.

**Comment by afilatoff** [comment]
So, you are saying your Maui.googleMaps is not really working in Windows environment. Using Mac is not really an option, I guess I need to find some alternatives

**Comment by plppp2001** [comment]
> So, you are saying your Maui.googleMaps is not really working in Windows environment. Using Mac is not really an option, I guess I need to find some alternatives

No he's saying don't run your iOS Simulator on your Windows computer. Run the Simulator or IPhone directly on the MAC computer. Uncheck the following in VS2022 on your windows VS:

![image](https://github.com/themronion/Maui.GoogleMaps/assets/45370058/c3562e2c-2433-42cf-adeb-47299d0b4832)

**Comment by themronion** [comment]
Its working just fine. Just don't use an iphone connected to a windows machine. Its not the problem of the lib, but more of a limitation of Hot Restart
> Using Mac is not really an option

I wish u good luck in creating an iOS app without a Mac :)

**Comment by afilatoff** [comment]
Ok, here my first attempt to use iPhone connected to Mac via USB and PC paired to Mac, used Automatic Provisioning, certificate "Apple Development: Created via API (D6AS23AP8Y)" added to Keychain on Mac and to my Apple account. First error  has something to do with GoogleMaps.bundle. Please let me know how to fix that.

Severity	Code	Description	Project	File	Line	Suppression State
Error (active)		/usr/bin/codesign exited with code 1:
Warning: unable to build chain to self-signed root for signer "Apple Development: Created via API (D6AS23AP8Y)"
/Users/....../Library/Caches/Xamarin/mtbs/builds/Towing/9b197fd6df90480daaa81ae53078b8cee43d5d78bec3b3e7649d2619371616df/bin/Debug/net8.0-ios/ios-arm64/device-builds/iphone15.3-17.2.1/Towing.app/GoogleMaps.bundle/GMSCoreResources.bundle/GMSShaders.metallib: errSecInternalComponent	Towing (net8.0-ios)	C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\17.2.8053\tools\msbuild\iOS\Xamarin.Shared.targets	2257

**Comment by afilatoff** [comment]
Any idea why your component causing this problem?

**Comment by themronion** [comment]
> Any idea why your component causing this problem?

It's not the problem of this lib. It's just you didn't manage to correctly create certificates and provision profiles for signing your app. Please use a little bit of google. Locking up this conv.
