### ISSUE TITLE
In the BasicMap View can not set MyLocationEnabled = true

### ISSUE THREAD

**Issue by Camuvingian** [themronion/Maui.GoogleMaps#7]
### VERSIONS

* Maui.GoogleMaps - latest main
* .NET SDK - x.x.x

### IDE

- [ ] Rider
- [x] Visual Studio
- [ ] Visual Studio for Mac

### PLATFORMS

- [x] Android
- [] iOS

### ACTUAL BEHAVIOR
```
When I select the MyLocationEnabled = true, I get an unhandled exception in MapHandler.cs line 249 (see screenshot)
```

### ACTUAL SCREENSHOTS/STACKTRACE

```
![image](https://user-images.githubusercontent.com/4823601/236445486-303099b6-aaec-4108-8c69-0c54c414a588.png)

<HTML>
<head>
<title>Document</title></head>
<body>
<!--StartFragment-->


  | Name | Value | Type
-- | -- | -- | --
◢ | $exception | {Java.Lang.SecurityException: my location requires permission ACCESS_FINE_LOCATION or ACCESS_COARSE_LOCATION    at Java.Interop.JniEnvironment.InstanceMethods.CallNonvirtualVoidMethod(JniObjectReference instance, JniObjectReference type, JniMethodInfo method, JniArgumentValue* args) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/obj/Release/net7.0/JniEnvironment.g.cs:line 12324    at Java.Interop.JniPeerMembers.JniInstanceMethods.InvokeNonvirtualVoidMethod(String encodedMember, IJavaPeerable self, JniArgumentValue* parameters) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.JniInstanceMethods_Invoke.cs:line 93    at Android.Gms.Maps.GoogleMap.set_MyLocationEnabled(Boolean value) in /Users/runner/work/1/s/generated/com.google.android.gms.play-services-maps/obj/Release/net6.0-android31.0/generated/src/Android.Gms.Maps.GoogleMap.cs:line 3669    at Maui.GoogleMaps.Handlers.MapHandler.MapMyLocationEnabled(MapHandler handler, Map map) in C:\Dev\Mobile\MAUI\showcase\Maui.GoogleMaps-maui\lib\Maui.GoogleMaps\Platforms\Android\MapHandler.cs:line 249    at Microsoft.Maui.PropertyMapper`2.<>c__DisplayClass5_0[[Maui.GoogleMaps.Map, Maui.GoogleMaps, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Maui.GoogleMaps.Handlers.MapHandler, Maui.GoogleMaps, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<Add>b__0(IElementHandler h, IElement v) in D:\a\_work\1\s\src\Core\src\PropertyMapper.cs:line 172    at Microsoft.Maui.PropertyMapper.UpdatePropertyCore(String key, IElementHandler viewHandler, IElement virtualView) in D:\a\_work\1\s\src\Core\src\PropertyMapper.cs:line 47    at Microsoft.Maui.PropertyMapper.UpdateProperty(IElementHandler viewHandler, IElement virtualView, String property) in D:\a\_work\1\s\src\Core\src\PropertyMapper.cs:line 72    at Microsoft.Maui.Handlers.ElementHandler.UpdateValue(String property) in D:\a\_work\1\s\src\Core\src\Handlers\Element\ElementHandler.cs:line 87    at Microsoft.Maui.Controls.Element.OnPropertyChanged(String propertyName) in D:\a\_work\1\s\src\Controls\src\Core\Element.cs:line 383    at Microsoft.Maui.Controls.BindableObject.SetValueActual(BindableProperty property, BindablePropertyContext context, Object value, Boolean currentlyApplying, SetValueFlags attributes, Boolean silent) in D:\a\_work\1\s\src\Controls\src\Core\BindableObject.cs:line 533    at Microsoft.Maui.Controls.BindableObject.SetValueCore(BindableProperty property, Object value, SetValueFlags attributes, SetValuePrivateFlags privateAttributes) in D:\a\_work\1\s\src\Controls\src\Core\BindableObject.cs:line 469    at Microsoft.Maui.Controls.BindableObject.SetValue(BindableProperty property, Object value, Boolean fromStyle, Boolean checkAccess) in D:\a\_work\1\s\src\Controls\src\Core\BindableObject.cs:line 391    at Microsoft.Maui.Controls.BindableObject.SetValue(BindableProperty property, Object value) in D:\a\_work\1\s\src\Controls\src\Core\BindableObject.cs:line 365    at Maui.GoogleMaps.Map.set_MyLocationEnabled(Boolean value) in C:\Dev\Mobile\MAUI\showcase\Maui.GoogleMaps-maui\lib\Maui.GoogleMaps\Map.cs:line 163    at MauiGoogleMapSample.BasicMapPage.<.ctor>b__0_1(Object sender, ToggledEventArgs e) in C:\Dev\Mobile\MAUI\showcase\Maui.GoogleMaps-maui\sample\MauiGoogleMapSample\BasicMapPage.xaml.cs:line 28    at Microsoft.Maui.Controls.Switch.<>c.<.cctor>b__27_0(BindableObject bindable, Object oldValue, Object newValue) in D:\a\_work\1\s\src\Controls\src\Core\Switch.cs:line 21    at Microsoft.Maui.Controls.BindableObject.SetValueActual(BindableProperty property, BindablePropertyContext context, Object value, Boolean currentlyApplying, SetValueFlags attributes, Boolean silent) in D:\a\_work\1\s\src\Controls\src\Core\BindableObject.cs:line 535    at Microsoft.Maui.Controls.BindableObject.SetValueCore(BindableProperty property, Object value, SetValueFlags attributes, SetValuePrivateFlags privateAttributes) in D:\a\_work\1\s\src\Controls\src\Core\BindableObject.cs:line 469    at Microsoft.Maui.Controls.BindableObject.SetValue(BindableProperty property, Object value, Boolean fromStyle, Boolean checkAccess) in D:\a\_work\1\s\src\Controls\src\Core\BindableObject.cs:line 391    at Microsoft.Maui.Controls.BindableObject.SetValue(BindableProperty property, Object value) in D:\a\_work\1\s\src\Controls\src\Core\BindableObject.cs:line 365    at Microsoft.Maui.Controls.Switch.set_IsToggled(Boolean value) in D:\a\_work\1\s\src\Controls\src\Core\Switch.cs:line 59    at Microsoft.Maui.Controls.Switch.Microsoft.Maui.ISwitch.set_IsOn(Boolean value) in D:\a\_work\1\s\src\Controls\src\Core\HandlerImpl\Switch.Impl.cs:line 35    at Microsoft.Maui.Handlers.SwitchHandler.OnCheckedChanged(Boolean isOn) in D:\a\_work\1\s\src\Core\src\Handlers\Switch\SwitchHandler.Android.cs:line 73    at Microsoft.Maui.Handlers.SwitchHandler.CheckedChangeListener.Android.Widget.CompoundButton.IOnCheckedChangeListener.OnCheckedChanged(CompoundButton buttonView, Boolean isToggled) in D:\a\_work\1\s\src\Core\src\Handlers\Switch\SwitchHandler.Android.cs:line 82    at Android.Widget.CompoundButton.IOnCheckedChangeListenerInvoker.n_OnCheckedChanged_Landroid_widget_CompoundButton_Z(IntPtr jnienv, IntPtr native__this, IntPtr native_buttonView, Boolean isChecked) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net7.0/android-33/mcw/Android.Widget.CompoundButton.cs:line 88    at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPLZ_V(_JniMarshal_PPLZ_V callback, IntPtr jnienv, IntPtr klazz, IntPtr p0, Boolean p1) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:line 176   --- End of managed Java.Lang.SecurityException stack trace --- java.lang.SecurityException: my location requires permission ACCESS_FINE_LOCATION or ACCESS_COARSE_LOCATION 	at com.google.maps.api.android.lib6.impl.ch.O(:com.google.android.gms.policy_maps_core_dynamite@231112107@231112103072.517507265.517507265:9) 	at com.google.android.gms.maps.internal.k.bn(:com.google.android.gms.policy_maps_core_dynamite@231112107@231112103072.517507265.517507265:179) 	at ayl.onTransact(:com.google.android.gms.policy_maps_core_dynamite@231112107@231112103072.517507265.517507265:4) 	at android.os.Binder.transact(Binder.java:1164) 	at com.google.android.gms.internal.maps.zza.zzc(com.google.android.gms:play-services-maps@@18.1.0:2) 	at com.google.android.gms.maps.internal.zzg.setMyLocationEnabled(com.google.android.gms:play-services-maps@@18.1.0:3) 	at com.google.android.gms.maps.GoogleMap.setMyLocationEnabled(com.google.android.gms:play-services-maps@@18.1.0:1) 	at crc64fcf28c0e24b4cc31.SwitchHandler_CheckedChangeListener.n_onCheckedChanged(Native Method) 	at crc64fcf28c0e24b4cc31.SwitchHandler_CheckedChangeListener.onCheckedChanged(SwitchHandler_CheckedChangeListener.java:31) 	at android.widget.CompoundButton.setChecked(CompoundButton.java:222) 	at androidx.appcompat.widget.SwitchCompat.setChecked(SwitchCompat.java:1183) 	at androidx.appcompat.widget.SwitchCompat.toggle(SwitchCompat.java:1178) 	at android.widget.CompoundButton.performClick(CompoundButton.java:144) 	at android.view.View.performClickInternal(View.java:7483) 	at android.view.View.-$Nest$mperformClickInternal(Unknown Source:0) 	at android.view.View$PerformClick.run(View.java:29334) 	at android.os.Handler.handleCallback(Handler.java:942) 	at android.os.Handler.dispatchMessage(Handler.java:99) 	at android.os.Looper.loopOnce(Looper.java:201) 	at android.os.Looper.loop(Looper.java:288) 	at android.app.ActivityThread.main(ActivityThread.java:7872) 	at java.lang.reflect.Method.invoke(Native Method) 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)    --- End of managed Java.Lang.SecurityException stack trace --- java.lang.SecurityException: my location requires permission ACCESS_FINE_LOCATION or ACCESS_COARSE_LOCATION 	at com.google.maps.api.android.lib6.impl.ch.O(:com.google.android.gms.policy_maps_core_dynamite@231112107@231112103072.517507265.517507265:9) 	at com.google.android.gms.maps.internal.k.bn(:com.google.android.gms.policy_maps_core_dynamite@231112107@231112103072.517507265.517507265:179) 	at ayl.onTransact(:com.google.android.gms.policy_maps_core_dynamite@231112107@231112103072.517507265.517507265:4) 	at android.os.Binder.transact(Binder.java:1164) 	at com.google.android.gms.internal.maps.zza.zzc(com.google.android.gms:play-services-maps@@18.1.0:2) 	at com.google.android.gms.maps.internal.zzg.setMyLocationEnabled(com.google.android.gms:play-services-maps@@18.1.0:3) 	at com.google.android.gms.maps.GoogleMap.setMyLocationEnabled(com.google.android.gms:play-services-maps@@18.1.0:1) 	at crc64fcf28c0e24b4cc31.SwitchHandler_CheckedChangeListener.n_onCheckedChanged(Native Method) 	at crc64fcf28c0e24b4cc31.SwitchHandler_CheckedChangeListener.onCheckedChanged(SwitchHandler_CheckedChangeListener.java:31) 	at android.widget.CompoundButton.setChecked(CompoundButton.java:222) 	at androidx.appcompat.widget.SwitchCompat.setChecked(SwitchCompat.java:1183) 	at androidx.appcompat.widget.SwitchCompat.toggle(SwitchCompat.java:1178) 	at android.widget.CompoundButton.performClick(CompoundButton.java:144) 	at android.view.View.performClickInternal(View.java:7483) 	at android.view.View.-$Nest$mperformClickInternal(Unknown Source:0) 	at android.view.View$PerformClick.run(View.java:29334) 	at android.os.Handler.handleCallback(Handler.java:942) 	at android.os.Handler.dispatchMessage(Handler.java:99) 	at android.os.Looper.loopOnce(Looper.java:201) 	at android.os.Looper.loop(Looper.java:288) 	at android.app.ActivityThread.main(ActivityThread.java:7872) 	at java.lang.reflect.Method.invoke(Native Method) 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936) } | Java.Lang.SecurityException


<!--EndFragment-->
</body>
</HTML>

```

### EXPECTED BEHAVIOR 
```
It should just switch on. 
```

### HOW TO REPRODUCE
```
Launch the sample application using VS2022 and launch on Android (I am using Pixel 5.0 API 33 (Android 13 API 33)).
```

**Comment by themronion** [comment]
Please read carefully the exception. It clearly states that you need to declare permissions and request them from the user before using this property.

**Comment by themronion** [comment]
Ah, i see you were talking about the sample app in the repo. Indeed it may have no permission requests, since it was mostly ported over from other repo. Need to check

**Comment by themronion** [comment]
fixed here: https://github.com/themronion/Maui.GoogleMaps/commit/a8db42b9b03eb04187eb8cab71d7c901f5138d6c

**Comment by Camuvingian** [comment]
Wow. Great work. Thank you!
