### ISSUE TITLE
 System.InvalidOperationException: PlatformView cannot be null here - MapHandler.get_NativeMap()

### ISSUE THREAD

**Issue by LeoJHarris** [themronion/Maui.GoogleMaps#87]
### VERSIONS

* Maui.GoogleMaps - 6.1.0
* .NET SDK - >NET 9.0

### IDE

- [ ] Rider
- [x] Visual Studio
- [ ] Visual Studio for Mac

### PLATFORMS

- [ ] Android
- [x] iOS

### ACTUAL BEHAVIOR

Navigating away from a page with the map throws the attached exception 

### ACTUAL SCREENSHOTS/STACKTRACE

```csharp
System.InvalidOperationException: PlatformView cannot be null here
   at Microsoft.Maui.Handlers.ViewHandler`2[[Maui.GoogleMaps.Map, Maui.GoogleMaps, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Google.Maps.MapView, Google.Maps, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].get_PlatformView()
   at Maui.GoogleMaps.Handlers.MapHandler.get_NativeMap()
   at Maui.GoogleMaps.Handlers.MapHandler.DisconnectHandler(MapView platformView)
   at Microsoft.Maui.Handlers.ViewHandler`2[[Maui.GoogleMaps.Map, Maui.GoogleMaps, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Google.Maps.MapView, Google.Maps, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].OnDisconnectHandler(UIView platformView)
   at Microsoft.Maui.Handlers.ViewHandler.OnDisconnectHandler(Object platformView)
   at Microsoft.Maui.Handlers.ElementHandler.DisconnectHandler(Object platformView)
   at Microsoft.Maui.Handlers.ElementHandler.Microsoft.Maui.IElementHandler.DisconnectHandler()
   at Microsoft.Maui.ViewExtensions.DisconnectHandlers(IView view)
   at Microsoft.Maui.Controls.Page.SendNavigatedFrom(NavigatedFromEventArgs args, Boolean disconnectHandlers)
   at Microsoft.Maui.Controls.NavigationPage.SendNavigated(Page previousPage, NavigationType navigationType)
   at Microsoft.Maui.Controls.NavigationPage.PopAsyncInner(Boolean animated, Boolean fast)
   at Microsoft.Maui.Controls.NavigationPage.PopAsync(Boolean animated)
[0:] START MAIN EXCEPTION########################################
[0:] System.InvalidOperationException: PlatformView cannot be null here
   at Microsoft.Maui.Handlers.ViewHandler`2[[Maui.GoogleMaps.Map, Maui.GoogleMaps, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Google.Maps.MapView, Google.Maps, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].get_PlatformView()
   at Maui.GoogleMaps.Handlers.MapHandler.get_NativeMap()
   at Maui.GoogleMaps.Handlers.MapHandler.DisconnectHandler(MapView platformView)
   at Microsoft.Maui.Handlers.ViewHandler`2[[Maui.GoogleMaps.Map, Maui.GoogleMaps, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Google.Maps.MapView, Google.Maps, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].OnDisconnectHandler(UIView platformView)
   at Microsoft.Maui.Handlers.ViewHandler.OnDisconnectHandler(Object platformView)
   at Microsoft.Maui.Handlers.ElementHandler.DisconnectHandler(Object platformView)
   at Microsoft.Maui.Handlers.ElementHandler.Microsoft.Maui.IElementHandler.DisconnectHandler()
   at Microsoft.Maui.ViewExtensions.DisconnectHandlers(IView view)
   at Microsoft.Maui.Controls.Page.SendNavigatedFrom(NavigatedFromEventArgs args, Boolean disconnectHandlers)
   at Microsoft.Maui.Controls.NavigationPage.SendNavigated(Page previousPage, NavigationType navigationType)
   at Microsoft.Maui.Controls.NavigationPage.PopAsyncInner(Boolean animated, Boolean fast)
   at Microsoft.Maui.Controls.NavigationPage.PopAsync(Boolean animated)
   at Prism.Navigation.PageNavigationService.GoBackInternalAsync(INavigationParameters parameters)
[0:] END MAIN EXCEPTION########################################
Thread started: <Thread Pool> #32
```

### EXPECTED BEHAVIOR 

Not to throw the exception.

### HOW TO REPRODUCE
Navigation back with a page with a Map

**Comment by eliebitar** [comment]
I am experiencing the same bug! Any updates on when it will be fixed?

**Comment by themronion** [comment]
Probably it is because of this: https://learn.microsoft.com/en-us/dotnet/maui/whats-new/dotnet-9?view=net-maui-9.0#handler-disconnection
Try playing with this property

**Comment by LeoJHarris** [comment]
@themronion its possible to set `HandlerProperties.DisconnectPolicy="Manual"` directly on the map and this changes the behavior of the control to pre .NET MAUI 9.0 but I was unable to see in the source code how the `NativeMap` is null.

```csharp
protected override void DisconnectHandler(MapView platformView)
{
    if (Map != null)
    {
        Map.OnSnapshot -= OnSnapshot;
        foreach (var logic in Logics)
        {
            logic.Unregister(NativeMap, Map);  <===== offending code here is NativeMap
        }
    }
    _cameraLogic.Unregister();
    _uiSettingsLogic.Unregister();

    var mkMapView = platformView;
    if (mkMapView != null)
    {
        mkMapView.CoordinateLongPressed -= CoordinateLongPressed;
        mkMapView.CoordinateTapped -= CoordinateTapped;
        mkMapView.CameraPositionChanged -= CameraPositionChanged;
        mkMapView.DidTapMyLocationButton = null;
    }

    base.DisconnectHandler(platformView);
}
```

**Comment by Th3L0x** [comment]
Same here :/
@LeoJHarris 
Could you clarify where exactly you added this code in your project? Did you override it in a custom Map control, or did you place it somewhere like App.xaml.cs or MauiProgram.cs?  Thanks!

**Comment by LeoJHarris** [comment]
@Th3L0x Directly on the map control like the following.

```xaml
 <maps:Map 
     HandlerProperties.DisconnectPolicy="Manual" 
     MapType="Street"  >
```

**Comment by themronion** [comment]
fixed in 6.2.0
